# Retail Store Sales Analysis (Core)

Author: Helene Schmelzer

Development Dates

Start: 01-05-2026

Finish: 02-05-2026

## Introduction to the Project

In this project stage, we will develop an initial analysis of a retail store sales dataset using NumPy. The objective is for students to apply the concepts learned in the course related to array manipulation, numerical operations, and basic data analysis. This exercise provides a strong foundation for future stages involving data visualization, advanced analysis, and predictive modeling. It will also be a valuable addition to the students' portfolios by demonstrating practical data analysis skills.

## Dataset Description

For this project, we will use a recent Kaggle dataset titled *Retail Sales Dataset* (2023–2024). This dataset contains detailed information about the daily sales of different products in a retail store. It can be downloaded from Kaggle: https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset

## Part 1: Basic Analysis with NumPy

In this first part of the project, students will perform an initial exploratory analysis of the dataset using NumPy. The objective is to become familiar with the data and carry out basic data manipulation and analysis operations.

### Instructions

#### 1. Initial Project Setup

- Create a GitHub repository for the project.  
- Set up two branches in the repository: `main` and `dev`.  
- Add a `README.md` file with a project description, installation instructions, and usage guidelines.

#### 2. Data Loading and Preprocessing

- Load the data from the CSV file using NumPy.  
- Perform basic preprocessing to ensure the dataset is clean and ready for analysis.

#### 3. Data Exploration

- Calculate the total sales per product category.  
- Calculate the average daily sales per product category.  
- Identify the product categories with the highest and lowest sales.

#### 4. Data Manipulation

- Filter the data to display only the sales of a specific product category.  
- Perform arithmetic operations (addition, subtraction, multiplication, and division) on the data to obtain additional statistics.

### Step-by-Step Guide

#### Setting Up the Project on GitHub

##### Creating a GitHub Repository

- Go to GitHub and create a new repository.  
- Name the repository, for example, `retail-sales-analysis`.

##### Cloning the Repository to Your Local Machine

Open your terminal and run the following commands to clone the repository:

```bash
git clone https://github.com/your-username/retail-sales-analysis.git
cd retail-sales-analysis
```

##### Creating `main` and `dev` Branches

Make sure you are on the `main` branch:

```bash
git checkout main
```

Create a new branch called `dev` and switch to it:

```bash
git checkout -b dev
```

##### Adding a `README.md` File

Create a `README.md` file with the following structure:

```markdown
# Retail Sales Analysis

This project analyzes retail store sales data using NumPy-based data analysis techniques.

## Project Structure

- `data/`: Contains the dataset files.
- `notebooks/`: Contains Jupyter notebooks for analysis.
- `src/`: Contains the project source code.
- `README.md`: Project documentation.

## Installation Instructions

1. Clone the repository: `git clone https://github.com/your-username/retail-sales-analysis.git`
2. Install the dependencies: `pip install -r requirements.txt`

## Usage

Run the Jupyter notebooks in the `notebooks` folder to perform the data analysis.
```

##### Committing and Pushing Changes

Stage and commit the changes:

```bash
git add README.md
git commit -m "Add README.md"
```

Push the changes to the remote repository:

```bash
git push origin dev
```

#### Hint: Loading Data with NumPy

```python
import numpy as np

def load_data(file_path):
    # Load CSV data using NumPy
    data = np.genfromtxt(file_path, delimiter=',', skip_header=1)
    return data

if __name__ == "__main__":
    file_path = '../data/retail_sales.csv'
    data = load_data(file_path)
    print(data)
```

## Previous analysis

### Dataset Availability and Path Setup

This section verifies that the dataset is available in the expected directory and sets up the file path for further analysis.

In [98]:
from pathlib import Path

In [99]:
data_dir = Path("../data")

# List available files (for verification)
available_files = list(data_dir.iterdir())
print("Available files:", available_files)

Available files: [WindowsPath('../data/retail_sales_dataset.csv')]

In [100]:
file_name = "retail_sales_dataset.csv"
dataset_path = data_dir / file_name

# Validate dataset existence
if not dataset_path.exists():
    raise FileNotFoundError(f"{file_name} not found in {data_dir}")

print("Dataset found at:", dataset_path)

Dataset found at: ..\data\retail_sales_dataset.csv

### Initial Data Assessment

- The dataset contains 1000 rows and 9 columns.
- The `Total Amount` column represents the sales value per transaction.
- There are no missing values in the dataset.
- No duplicated rows were found.
- The Date column is stored as a string and should be converted to datetime format for time-based analysis.
- Some columns (e.g., Transaction ID, Customer ID, Gender, Age) are not required for the current analysis but may be useful for further exploration.
- No inconsistencies were found in categorical variables such as `Product Category` and `Gender`.

In [101]:
import pandas as pd

In [102]:
df = pd.read_csv(dataset_path)

In [103]:
print(f"{file_name}")
print(f"Shape: {df.shape}")
print(f"→ {df.shape[0]} rows, {df.shape[1]} columns\n")

retail_sales_dataset.csv
Shape: (1000, 9)
→ 1000 rows, 9 columns

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [105]:
df.describe().round(2)

       Transaction ID      Age  Quantity  Price per Unit  Total Amount
count         1000.00  1000.00   1000.00         1000.00        1000.0
mean           500.50    41.39      2.51          179.89         456.0
std            288.82    13.68      1.13          189.68         560.0
min              1.00    18.00      1.00           25.00          25.0
25%            250.75    29.00      1.00           30.00          60.0
50%            500.50    42.00      3.00           50.00         135.0
75%            750.25    53.00      4.00          300.00         900.0
max           1000.00    64.00      4.00          500.00        2000.0

In [106]:
n_duplicated = df.duplicated().sum()
print(f"Duplicated rows: {n_duplicated}")

Duplicated rows: 0

In [107]:
print(df['Product Category'].value_counts())

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [108]:
print(df['Gender'].value_counts())

Gender
Female    510
Male      490
Name: count, dtype: int64

In [109]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

### Sample Records Inspection

We inspect the first and last rows of the dataset to understand its structure, column formatting, and verify that the data has been loaded correctly.
- Each row represents a single transaction.
- The dataset includes product category, quantity, and pricing information.
- The Total Amount column appears to be derived from quantity and unit price.
- The data structure is consistent across rows.

In [110]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [111]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [112]:
(df['Quantity'] * df['Price per Unit'] == df['Total Amount']).all()

np.True_

### Analysis Objectives and Required Metrics

The following metrics define the objectives of the analysis and guide the data transformations required.

**Core Metrics**
- **Total sales per product category**

    Uses: `Product Category`, `Total Amount`

- **Average daily sales per product category**

    Uses: `Date`, `Product Category`, `Total Amount`

- **Product categories with the highest and lowest sales**

    Uses: `Product Category`, `Total Amount`

**Additional Metrics**
- **Average order value per category**

    Uses: `Product Category`, `Total Amount`

- **Total quantity sold per category**

    Uses: `Product Category`, `Quantity`

### Data Loading with NumPy

NumPy was evaluated for data loading, but handling mixed data types proved inefficient. Even when forcing string-based loading, the resulting structure lacked flexibility for tabular analysis.

For this reason, Pandas was selected as the primary tool for data loading and preprocessing.

In [113]:
import numpy as np

#### Final Attempt Before Using Pandas

In [114]:
data_plain_text = np.genfromtxt(
    dataset_path,
    delimiter=',',
    dtype=str,
    skip_header=1
)
data = data_plain_text
data

array([['1', '2023-11-24', 'CUST001', ..., '3', '50', '150'],
       ['2', '2023-02-27', 'CUST002', ..., '2', '500', '1000'],
       ['3', '2023-01-13', 'CUST003', ..., '1', '30', '30'],
       ...,
       ['998', '2023-10-29', 'CUST998', ..., '4', '25', '100'],
       ['999', '2023-12-05', 'CUST999', ..., '3', '50', '150'],
       ['1000', '2023-04-12', 'CUST1000', ..., '4', '30', '120']],
      shape=(1000, 9), dtype='<U11')

## Data Cleaning

### Formatting `Date` column

To preserve the original dataset, a copy of the DataFrame is created. 
Unlike simple assignment, which creates a reference to the same object, the `.copy()` method creates an independent DataFrame in memory.

The `Date` column is converted to a datetime data type using pandas, enabling temporal operations such as filtering and sorting.

Invalid or non-parseable values are coerced into `NaT` to prevent errors and allow identification of problematic entries.

It is now possible to apply temporal filters based on the `Date` column.

No missing values were found in the dataset after validation using `.isna().sum()`.  

Therefore, no further action was required for handling missing data.

In [115]:
df_clean = df.copy()

Check if the conversion ended successfully.
Invalid dates become `NaT` instead of crashing.

In [116]:
df_clean["Date"] = pd.to_datetime(df_clean["Date"], errors="coerce")
df_clean["Date"].isna().sum()

np.int64(0)

In [117]:
df_clean[df_clean["Date"].isna()]

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

In [118]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [119]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[us]
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[us](1), int64(5), str(3)
memory usage: 70.4 KB

In [120]:
df_clean.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

### Selecting relevant columns

A subset of the dataset is created to focus the analysis on the relevant variables.  
The original cleaned dataset is preserved to maintain flexibility for future steps.

Columns `Gender` and `Age` were included to provide demographic context for the analysis results.

In [121]:
columns_needed = ["Date", "Product Category", "Quantity", "Total Amount", "Gender", "Age"]

df_analysis = df_clean[columns_needed].copy()

In [122]:
df_analysis.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              1000 non-null   datetime64[us]
 1   Product Category  1000 non-null   str
 2   Quantity          1000 non-null   int64
 3   Total Amount      1000 non-null   int64
 4   Gender            1000 non-null   str
 5   Age               1000 non-null   int64
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 47.0 KB

In [123]:
df_analysis.head()

        Date Product Category  Quantity  Total Amount  Gender  Age
0 2023-11-24           Beauty         3           150    Male   34
1 2023-02-27         Clothing         2          1000  Female   26
2 2023-01-13      Electronics         1            30    Male   50
3 2023-05-21         Clothing         1           500    Male   37
4 2023-05-06           Beauty         2           100    Male   30