# Retail Store Sales Analysis (Core)

This notebook analyzes retail sales data to understand category performance and customer behavior using key business metrics.

Author: Helene Schmelzer

Development Dates

Start: 01-05-2026

Finish: 03-05-2026

## Introduction to the Project

In this project stage, we will develop an initial analysis of a retail store sales dataset using NumPy. The objective is for students to apply the concepts learned in the course related to array manipulation, numerical operations, and basic data analysis. This exercise provides a strong foundation for future stages involving data visualization, advanced analysis, and predictive modeling. It will also be a valuable addition to the students' portfolios by demonstrating practical data analysis skills.

## Dataset Description

For this project, we will use a recent Kaggle dataset titled *Retail Sales Dataset* (2023–2024). This dataset contains detailed information about the daily sales of different products in a retail store. It can be downloaded from Kaggle: https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset

## Part 1: Basic Analysis with NumPy

In this first part of the project, students will perform an initial exploratory analysis of the dataset using NumPy. The objective is to become familiar with the data and carry out basic data manipulation and analysis operations.

### Instructions

#### 1. Initial Project Setup

- Create a GitHub repository for the project.  
- Set up two branches in the repository: `main` and `dev`.  
- Add a `README.md` file with a project description, installation instructions, and usage guidelines.

#### 2. Data Loading and Preprocessing

- Load the data from the CSV file using NumPy.  
- Perform basic preprocessing to ensure the dataset is clean and ready for analysis.

#### 3. Data Exploration

- Calculate the total sales per product category.  
- Calculate the average daily sales per product category.  
- Identify the product categories with the highest and lowest sales.

#### 4. Data Manipulation

- Filter the data to display only the sales of a specific product category.  
- Perform arithmetic operations (addition, subtraction, multiplication, and division) on the data to obtain additional statistics.

### Step-by-Step Guide

#### Setting Up the Project on GitHub

##### Creating a GitHub Repository

- Go to GitHub and create a new repository.  
- Name the repository, for example, `retail-sales-analysis`.

##### Cloning the Repository to Your Local Machine

Open your terminal and run the following commands to clone the repository:

```bash
git clone https://github.com/your-username/retail-sales-analysis.git
cd retail-sales-analysis
```

##### Creating `main` and `dev` Branches

Make sure you are on the `main` branch:

```bash
git checkout main
```

Create a new branch called `dev` and switch to it:

```bash
git checkout -b dev
```

##### Adding a `README.md` File

Create a `README.md` file with the following structure:

```markdown
# Retail Sales Analysis

This project analyzes retail store sales data using NumPy-based data analysis techniques.

## Project Structure

- `data/`: Contains the dataset files.
- `notebooks/`: Contains Jupyter notebooks for analysis.
- `src/`: Contains the project source code.
- `README.md`: Project documentation.

## Installation Instructions

1. Clone the repository: `git clone https://github.com/your-username/retail-sales-analysis.git`
2. Install the dependencies: `pip install -r requirements.txt`

## Usage

Run the Jupyter notebooks in the `notebooks` folder to perform the data analysis.
```

##### Committing and Pushing Changes

Stage and commit the changes:

```bash
git add README.md
git commit -m "Add README.md"
```

Push the changes to the remote repository:

```bash
git push origin dev
```

#### Hint: Loading Data with NumPy

```python
import numpy as np

def load_data(file_path):
    # Load CSV data using NumPy
    data = np.genfromtxt(file_path, delimiter=',', skip_header=1)
    return data

if __name__ == "__main__":
    file_path = '../data/retail_sales.csv'
    data = load_data(file_path)
    print(data)
```

## Previous analysis

### Dataset Availability and Path Setup

This section verifies that the dataset is available in the expected directory and sets up the file path for further analysis.

In [95]:
from pathlib import Path

In [96]:
data_dir = Path("../data")

# List available files (for verification)
available_files = list(data_dir.iterdir())
print("Available files:", available_files)

Available files: [WindowsPath('../data/retail_sales_dataset.csv')]

In [97]:
file_name = "retail_sales_dataset.csv"
dataset_path = data_dir / file_name

# Validate dataset existence
if not dataset_path.exists():
    raise FileNotFoundError(f"{file_name} not found in {data_dir}")

print("Dataset found at:", dataset_path)

Dataset found at: ..\data\retail_sales_dataset.csv

### Initial Data Assessment

- The dataset contains 1000 rows and 9 columns.
- The `Total Amount` column represents the sales value per transaction.
- There are no missing values in the dataset.
- No duplicated rows were found.
- The Date column is stored as a string and should be converted to datetime format for time-based analysis.
- Some columns (e.g., Transaction ID, Customer ID, Gender, Age) are not required for the current analysis but may be useful for further exploration.
- No inconsistencies were found in categorical variables such as `Product Category` and `Gender`.

In [98]:
import pandas as pd

In [99]:
df = pd.read_csv(dataset_path)

In [100]:
print(f"{file_name}")
print(f"Shape: {df.shape}")
print(f"→ {df.shape[0]} rows, {df.shape[1]} columns\n")

retail_sales_dataset.csv
Shape: (1000, 9)
→ 1000 rows, 9 columns

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [102]:
df.describe().round(2)

       Transaction ID      Age  Quantity  Price per Unit  Total Amount
count         1000.00  1000.00   1000.00         1000.00        1000.0
mean           500.50    41.39      2.51          179.89         456.0
std            288.82    13.68      1.13          189.68         560.0
min              1.00    18.00      1.00           25.00          25.0
25%            250.75    29.00      1.00           30.00          60.0
50%            500.50    42.00      3.00           50.00         135.0
75%            750.25    53.00      4.00          300.00         900.0
max           1000.00    64.00      4.00          500.00        2000.0

In [103]:
n_duplicated = df.duplicated().sum()
print(f"Duplicated rows: {n_duplicated}")

Duplicated rows: 0

In [104]:
print(df['Product Category'].value_counts())

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [105]:
print(df['Gender'].value_counts())

Gender
Female    510
Male      490
Name: count, dtype: int64

### Sample Records Inspection

We inspect the first and last rows of the dataset to understand its structure, column formatting, and verify that the data has been loaded correctly.
- Each row represents a single transaction.
- The dataset includes product category, quantity, and pricing information.
- The Total Amount column appears to be derived from quantity and unit price.
- The data structure is consistent across rows.

In [106]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [107]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [108]:
(df['Quantity'] * df['Price per Unit'] == df['Total Amount']).all()

np.True_

### Analysis Objectives and Required Metrics

The following metrics define the objectives of the analysis and guide the data transformations required.

**Core Metrics**
- **Total sales per product category**

    Uses: `Product Category`, `Total Amount`

- **Average daily sales per product category**

    Uses: `Date`, `Product Category`, `Total Amount`

- **Product categories with the highest and lowest sales**

    Uses: `Product Category`, `Total Amount`

**Additional Metrics**
- **Average order value per category**

    Uses: `Product Category`, `Total Amount`

- **Total quantity sold per category**

    Uses: `Product Category`, `Quantity`

### Data Loading with NumPy

NumPy was evaluated for data loading, but handling mixed data types proved inefficient. Even when forcing string-based loading, the resulting structure lacked flexibility for tabular analysis.

For this reason, Pandas was selected as the primary tool for data loading and preprocessing.

In [109]:
import numpy as np

#### Final Attempt Before Using Pandas

In [110]:
data_plain_text = np.genfromtxt(
    dataset_path,
    delimiter=',',
    dtype=str,
    skip_header=1
)
data = data_plain_text
data

array([['1', '2023-11-24', 'CUST001', ..., '3', '50', '150'],
       ['2', '2023-02-27', 'CUST002', ..., '2', '500', '1000'],
       ['3', '2023-01-13', 'CUST003', ..., '1', '30', '30'],
       ...,
       ['998', '2023-10-29', 'CUST998', ..., '4', '25', '100'],
       ['999', '2023-12-05', 'CUST999', ..., '3', '50', '150'],
       ['1000', '2023-04-12', 'CUST1000', ..., '4', '30', '120']],
      shape=(1000, 9), dtype='<U11')

## Data Cleaning

### Formatting `Date` column

To preserve the original dataset, a copy of the DataFrame is created. 
Unlike simple assignment, which creates a reference to the same object, the `.copy()` method creates an independent DataFrame in memory.

The `Date` column is converted to a datetime data type using pandas, enabling temporal operations such as filtering and sorting.

Invalid or non-parseable values are coerced into `NaT` to prevent errors and allow identification of problematic entries.

It is now possible to apply temporal filters based on the `Date` column.

No missing values were found in the dataset after validation using `.isna().sum()`.  

Therefore, no further action was required for handling missing data.

In [111]:
df_clean = df.copy()

Check if the conversion ended successfully.
Invalid dates become `NaT` instead of crashing.

In [112]:
df_clean["Date"] = pd.to_datetime(df_clean["Date"], errors="coerce")
df_clean["Date"].isna().sum()

np.int64(0)

In [113]:
df_clean[df_clean["Date"].isna()]

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

In [114]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [115]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[us]
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[us](1), int64(5), str(3)
memory usage: 70.4 KB

In [116]:
df_clean.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

### Selecting Relevant Columns

A subset of the dataset is created to focus the analysis on the relevant variables.  
The original cleaned dataset is preserved to maintain flexibility for future steps.

Columns `Gender` and `Age` were included to provide demographic context for the analysis results.

In [117]:
columns_needed = ["Date", "Product Category", "Quantity", "Total Amount", "Gender", "Age"]

df_analysis = df_clean[columns_needed].copy()

In [118]:
df_analysis.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              1000 non-null   datetime64[us]
 1   Product Category  1000 non-null   str
 2   Quantity          1000 non-null   int64
 3   Total Amount      1000 non-null   int64
 4   Gender            1000 non-null   str
 5   Age               1000 non-null   int64
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 47.0 KB

In [119]:
df_analysis.head()

        Date Product Category  Quantity  Total Amount  Gender  Age
0 2023-11-24           Beauty         3           150    Male   34
1 2023-02-27         Clothing         2          1000  Female   26
2 2023-01-13      Electronics         1            30    Male   50
3 2023-05-21         Clothing         1           500    Male   37
4 2023-05-06           Beauty         2           100    Male   30

## Analysis

### Core Metrics

#### Total Sales per Product Category

Pandas was used for data selection and filtering, while NumPy was used to perform aggregation operations.

A short function was implemented to improve the readability of the results.

Sales are relatively evenly distributed across categories, with each contributing between 31% and 34% of total revenue. Electronics shows the highest share, while Beauty contributes the least, although the differences are small.

In [120]:
categories = df_analysis["Product Category"].unique()

In [121]:
sales_per_category =  {}

for category in categories:
    condition = df_analysis["Product Category"] == category
    total_sales = np.sum(df_analysis.loc[condition, "Total Amount"])
    sales_per_category[category] = total_sales

In [122]:
def format_number(n):
    """
    Replace thousand separator by . and decimal separator by ,
    """
    return f"{n:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

In [123]:
def sorted_dict(messy_dict: dict):
    """
    Sort a dict from highest to lower value.
    """
    return sorted(
        messy_dict.items(),
        key=lambda x: x[1],
        reverse=True
        )

In [124]:
sorted_sales_per_categories = sorted(
    sales_per_category.items(),
    key=lambda x: x[1],
    reverse=True
)

In [125]:
max_len = max(len(cat) for cat in categories) + 4
sorted_sales_per_categories = sorted_dict(sales_per_category)

print("\nTotal Sales per Product Category\n")
print(f"{'Category':<{max_len}}{'Total Sales':>17}")
print("-" * (max_len + 17))

for category, total_sales in sorted_sales_per_categories:
    print(f"{category:<{max_len}}{format_number(total_sales):>17}")

Total Sales per Product Category

Category             Total Sales
--------------------------------
Electronics           156.905,00
Clothing              155.580,00
Beauty                143.515,00

In [126]:
total_sales_all = sum(sales_per_category.values())

print("\nCategory Contribution (%)\n")
print(f"{'Category':<{max_len}}{'% Contribution':>17}")
print("-" * 32)

for category, total_sales in sorted_sales_per_categories:
    percentage = (total_sales / total_sales_all) * 100
    print(f"{category:<{max_len}}{format_number(percentage):>16}%")

Category Contribution (%)

Category          % Contribution
--------------------------------
Electronics               34,41%
Clothing                  34,12%
Beauty                    31,47%

#### Average Daily Sales per Product Category

Average daily sales per category follow the same pattern as total sales, with minimal variation between categories. This indicates that revenue is evenly distributed across categories, although this metric does not capture variability between individual days.

While average daily sales are stable across categories, transaction counts vary across days, ranging from 1 to 11 purchases.

In [127]:
average_daily_sales = {}

num_days = df_analysis["Date"].nunique()

for category, total_sales in sales_per_category.items():
    avg = total_sales / num_days
    average_daily_sales[category] = avg

In [128]:
sorted_averages = sorted_dict(average_daily_sales)

print("\nAverage Daily Sales per Product Category\n")
print(f"{'Category':<{max_len}}{'Avg Daily Sales':>25}")
print("-" * (max_len + 25))

for category, avg in sorted_averages:
    print(f"{category:<{max_len}}{format_number(avg):>25}")

Average Daily Sales per Product Category

Category                 Avg Daily Sales
----------------------------------------
Electronics                       454,80
Clothing                          450,96
Beauty                            415,99

In [129]:
daily_transactions = df_analysis["Date"].value_counts()

print("\nTop 5 Days by Transaction Count\n")
print(daily_transactions.head())

Top 5 Days by Transaction Count

Date
2023-05-16    11
2023-07-14    10
2023-05-23     9
2023-08-05     8
2023-02-05     8
Name: count, dtype: int64

In [130]:
min_tx = daily_transactions.min()
max_tx = daily_transactions.max()

print(f"\nTransaction counts range from {min_tx} to {max_tx} purchases.")

Transaction counts range from 1 to 11 purchases.

#### Product Categories with the Highest and Lowest Sales

Electronics shows the highest total sales, while Beauty records the lowest. However, the differences between categories are small, reinforcing the overall balanced distribution of revenue.

Transaction volume shows moderate variation across categories, with Clothing recording the highest number of purchases and Beauty the lowest. Combined with similar total revenue, this suggests that categories differ in purchasing patterns, with some categories rely more on higher transaction frequency, while others generate similar revenue through higher-value purchases.

In [131]:
highest_category, highest_value = sorted_sales_per_categories[0]
lowest_category, lowest_value = sorted_sales_per_categories[-1]

In [132]:
print("\nHighest and Lowest Sales by Category\n")

print(f"Highest: {highest_category:<{max_len}} ({format_number(highest_value)})")
print(f"Lowest : {lowest_category:<{max_len}} ({format_number(lowest_value)})")

Highest and Lowest Sales by Category

Highest: Electronics     (156.905,00)
Lowest : Beauty          (143.515,00)

In [133]:
transactions_per_category = {}

for category in categories:
    condition = df_analysis["Product Category"] == category
    count = np.sum(condition)  # True = 1, False = 0
    transactions_per_category[category] = count

In [134]:
sorted_transactions = sorted_dict(transactions_per_category)

In [135]:
print("\nTransactions per Product Category\n")
print(f"{'Category':<{max_len}}{'Transactions':>18}")
print("-" * (max_len + 18))

for category, count in sorted_transactions:
    print(f"{category:<{max_len}}{count:>18}")

Transactions per Product Category

Category             Transactions
---------------------------------
Clothing                      351
Electronics                   342
Beauty                        307

In [136]:
top_cat, top_count = sorted_transactions[0]
low_cat, low_count = sorted_transactions[-1]

In [137]:
print("\nHighest and Lowest Transactions by Category\n")

print(f"Highest: {top_cat:<{max_len}} ({top_count})")
print(f"Lowest : {low_cat:<{max_len}} ({low_count})")

Highest and Lowest Transactions by Category

Highest: Clothing        (351)
Lowest : Beauty          (307)

### Addional Metrics

#### Average Order Value per Category

The Average Order Value (AOV) was analyzed across product categories and further segmented by gender and age group to better understand customer behavior.

Initial results showed relatively small differences in AOV across categories, indicating that product category alone is not a strong differentiator of customer spending.

When incorporating demographic segmentation, the Electronics · Male · 51–65 segment emerged as the most valuable, combining high average order value with strong total revenue contribution.

Further analysis identified underperforming segments with high potential. In particular, the Clothing · Female · 18–25 segment stands out: despite generating relatively low revenue and order volume, it exhibits one of the highest AOVs.

This suggests that customers in this segment are willing to spend more per purchase but are not purchasing frequently, representing an opportunity to increase revenue by improving engagement and conversion.

A similar pattern is observed in the Electronics · Female · 18–25 segment, though with slightly higher activity and therefore lower relative upside.

In [138]:
df_analysis['Age Group'] = pd.cut(
    df_analysis['Age'],
    bins=[18, 25, 35, 50, 65],
    labels=['18-25', '26-35', '36-50', '51-65']
)

In [139]:
segment_metrics = (
    df_analysis.groupby(['Product Category', 'Gender', 'Age Group'])
        .agg(
            total_revenue=('Total Amount', 'sum'),
            avg_order_value=('Total Amount', 'mean'),
            orders=('Total Amount', 'count')
        )
    .reset_index()
)

In [140]:
segment_metrics['value_score'] = (
    (segment_metrics['total_revenue'] / segment_metrics['total_revenue'].max()) * 0.6 +
    (segment_metrics['avg_order_value'] / segment_metrics['avg_order_value'].max()) * 0.3 +
    (segment_metrics['orders'] / segment_metrics['orders'].max()) * 0.1
)

In [141]:
low_revenue_threshold = segment_metrics['total_revenue'].quantile(0.30)
low_orders_threshold = segment_metrics['orders'].quantile(0.30)
high_aov_threshold = segment_metrics['avg_order_value'].quantile(0.70)

underperforming_high_potential = segment_metrics[
    (segment_metrics['total_revenue'] < low_revenue_threshold) &
    (segment_metrics['orders'] < low_orders_threshold) &
    (segment_metrics['avg_order_value'] > high_aov_threshold)
]

# Minimum orders
underperforming_high_potential = underperforming_high_potential[
    underperforming_high_potential['orders'] >= 5
]

In [142]:
# Top segments (business value)
top_segments = segment_metrics.sort_values(by='value_score', ascending=False).round(2)

top_segments

,Product Category,Gender,Age Group,total_revenue,avg_order_value,orders,value_score
23,Electronics,Male,51-65,31035,500.56,62,0.92
22,Electronics,Male,36-50,26365,479.36,55,0.81
6,Beauty,Male,36-50,24875,578.49,43,0.81
10,Clothing,Female,36-50,25345,408.79,62,0.77
2,Beauty,Female,36-50,24235,494.59,49,0.77
19,Electronics,Female,51-65,24270,485.40,50,0.77
11,Clothing,Female,51-65,24785,420.08,59,0.76
13,Clothing,Male,26-35,20655,503.78,41,0.69
9,Clothing,Female,26-35,19320,585.45,33,0.69
15,Clothing,Male,51-65,21335,395.09,54,0.68
18,Electronics,Female,36-50,21210,400.19,53,0.67
1,Beauty,Female,26-35,18750,520.83,36,0.65
4,Beauty,Male,18-25,16080,670.00,24,0.65
3,Beauty,Female,51-65,18410,375.71,49,0.60
17,Electronics,Female,26-35,17045,448.55,38,0.59
14,Clothing,Male,36-50,17630,345.69,51,0.58
12,Clothing,Male,18-25,13175,487.96,27,0.52
16,Electronics,Female,18-25,12040,501.67,24,0.50
20,Electronics,Male,18-25,12550,432.76,29,0.48
7,Beauty,Male,51-65,13475,345.51,39,0.48
5,Beauty,Male,26-35,12490,402.90,31,0.47
8,Clothing,Female,18-25,9250,544.12,17,0.45
21,Electronics,Male,26-35,10220,393.08,26,0.42
0,Beauty,Female,18-25,10240,379.26,27,0.41

**Recommendation:**

> Focus on retaining and maximizing these high-value segments through loyalty programs, personalized offers, and premium product positioning, as they are the primary drivers of revenue.

In [143]:
# Opportunity segments
opportunity_segments = underperforming_high_potential.sort_values(
    by='avg_order_value', ascending=False
).round(2)

opportunity_segments

,Product Category,Gender,Age Group,total_revenue,avg_order_value,orders,value_score
8,Clothing,Female,18-25,9250,544.12,17,0.45
16,Electronics,Female,18-25,12040,501.67,24,0.50

**Recommendation:**

> Increase purchase frequency (used here as a proxy for customer engagement) in these segments through targeted marketing campaigns and tailored promotions, as customers already demonstrate strong spending potential.

#### Total Quantity Sold per Category

Clothing shows the highest sales volume, with Electronics close behind, indicating relatively consistent demand across these categories. Beauty has the lowest quantity sold, suggesting comparatively lower demand or a more niche positioning.

Despite these differences in volume, revenue is evenly distributed across all product categories, with each contributing roughly one-third of total sales. This indicates a balanced business without over-reliance on a single category.

In [148]:
df_analysis.groupby('Product Category')['Quantity'].sum()

Product Category
Beauty         771
Clothing       894
Electronics    849
Name: Quantity, dtype: int64

In [145]:
df_analysis.groupby('Product Category')['Total Amount'].sum()

Product Category
Beauty         143515
Clothing       155580
Electronics    156905
Name: Total Amount, dtype: int64

To better compare performance across categories, quantity, revenue, and average order value were combined into a single summary table:

In [146]:
category_summary = (
    df_analysis.groupby('Product Category')
        .agg(
            total_quantity=('Quantity', 'sum'),
            total_revenue=('Total Amount', 'sum'),
            avg_order_value=('Total Amount', 'mean')
        )
        .reset_index()
)

# Add revenue contribution
category_summary['revenue_share_%'] = (
    category_summary['total_revenue'] / category_summary['total_revenue'].sum()
) * 100

category_summary = category_summary.round(2)

In [147]:
category_summary.sort_values(by='revenue_share_%', ascending=False)

,Product Category,total_quantity,total_revenue,avg_order_value,revenue_share_%
2,Electronics,849,156905,458.79,34.41
1,Clothing,894,155580,443.25,34.12
0,Beauty,771,143515,467.48,31.47

**Insights:**

> All categories contribute similarly to total revenue, with no clear dominant category. Clothing leads in volume, while Beauty shows slightly higher average order value, indicating different performance drivers across categories.

**Recommendation:**

> Maintain a balanced strategy across categories while optimizing their individual strengths: support volume in Clothing, improve demand generation in Beauty, and sustain the balanced performance of Electronics.

## Executive Summary

This analysis examined sales performance across product categories using core metrics such as total sales, average daily sales, and category-level performance, complemented by additional metrics including average order value (AOV), total quantity sold, and customer segmentation.

Overall, the business demonstrates a **balanced distribution of revenue across product categories**, with each category contributing a similar share of total sales. Both total sales and average daily sales confirm consistent performance across categories, with no single category significantly outperforming or underperforming others.

From a demand perspective, **Clothing** shows the highest sales volume, indicating strong and consistent customer demand, while **Electronics** maintains a balanced profile across revenue, volume, and order value. Beauty, despite having the lowest quantity sold, achieves a relatively higher average order value, suggesting stronger spending per transaction but lower purchase frequency.

Customer segmentation highlights that **Electronics · Male · 51–65** is the most valuable segment, contributing significantly to overall revenue. Additionally, **Clothing · Female · 18–25** emerges as a high-potential segment: although it currently generates lower revenue and order volume, it exhibits a high AOV, indicating an opportunity to increase engagement and drive growth.

### Key Takeaways

- Revenue is evenly distributed across categories, indicating a stable and diversified business.
- Clothing is the primary volume driver, while Electronics maintains balanced performance.
- Beauty shows lower demand but higher spending per purchase, indicating potential for growth.
- Younger female customers (18–25) represent an underpenetrated but high-value opportunity.

### Recommendations

- **Maintain balanced category performance:** Continue supporting all categories to preserve revenue diversification while optimizing individual strengths.
- **Leverage high-performing segments:** Focus on retention and personalization strategies for key segments such as Electronics · Male · 51–65.
- **Activate high-potential segments:** Increase engagement in segments like Clothing · Female · 18–25 through targeted campaigns and incentives.
- **Enhance category strategies:**
    - Support demand and inventory in Clothing
    - Strengthen conversion and engagement in Beauty
    - Maintain stable performance in Electronics