# Retail Store Sales Analysis using Pandas (Core)

## Part III: Data Transformation and Advanced Analysis using Pandas

Author: heleneInsights

Development Date

Start: 07-05-2026

Finish: 08-05-2026

## Introduction to the Project

In this stage of the project, the retail sales dataset was analyzed using the Pandas library. Different data transformation and analysis techniques were applied in order to better understand customer behavior, product performance, and sales patterns.

The project focuses on the use of:

- data transformation,
- grouping and aggregation,
- statistical analysis,
- and the `apply()` method for custom calculations.

This stage also prepares the dataset for future work involving:

- data visualization,
- exploratory data analysis,
- and predictive modeling techniques.

## Dataset Description

In this project, we will use the Retail Sales Dataset (2023–2024) available on Kaggle. This dataset contains detailed records of daily sales transactions from a retail store, including information about products, quantities sold, pricing, and dates.

The dataset can be downloaded from Kaggle:
https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset

## Brief Observations and Insights

During the analysis, several patterns and relationships were identified in the retail sales data. By using grouping, aggregation, and transformation techniques in Pandas, it was possible to compare customer spending behavior across different product categories, age groups, and price levels.

The creation of new columns such as `Age Group`, `Spending Category`, `Price Tier`, and `Month` helped simplify the analysis and made the results easier to interpret.

Additionally, statistical measures such as mean, standard deviation, variance, minimum, and maximum values were used to better understand sales distribution and purchasing behavior across different groups.

The use of the `apply()` method also allowed the implementation of custom calculations, making the analysis more flexible and detailed.

## Previous analysis

### Dataset Availability and Path Setup

In [61]:
from pathlib import Path

In [62]:
data_dir = Path("../data")

# List available files (for verification)
available_files = list(data_dir.iterdir())
print("Available files:", available_files)

Available files: [WindowsPath('../data/retail_sales_dataset.csv')]

In [63]:
file_name = "retail_sales_dataset.csv"
dataset_path = data_dir / file_name

# Validate dataset existence
if not dataset_path.exists():
    raise FileNotFoundError(f"{file_name} not found in {data_dir}")

print("Dataset found at:", dataset_path)

Dataset found at: ..\data\retail_sales_dataset.csv

In this part of the project, we begin working with Pandas to explore and analyze the dataset.

Before starting the analysis, the following steps were already completed:

- Pandas was installed
- The dataset was downloaded from Kaggle
- The CSV file was placed inside the working directory

Next, Pandas is imported in order to load and manipulate the dataset.

In [64]:
import pandas as pd

### Data Loading

The dataset is loaded into a Pandas DataFrame from a CSV file:

In [65]:
df = pd.read_csv(dataset_path)

The first 10 rows are displayed to obtain an initial overview of the dataset structure, columns, and sample values.

In [66]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

This initial inspection helps verify that the dataset was loaded correctly and provides a quick understanding of the available information.

### Initial Data Assessment

The dataset was explored to better understand its structure and identify possible data quality issues.

In [67]:
print(f"{file_name}")
print(f"Shape: {df.shape}")
print(f"→ {df.shape[0]} rows, {df.shape[1]} columns\n")

retail_sales_dataset.csv
Shape: (1000, 9)
→ 1000 rows, 9 columns

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

This inspection provides information about:

- the number of rows and columns,
- column names,
- data types,
- and the presence of missing values.

During the assessment, it was identified that the `Date` column was stored as a string (`str`) instead of a datetime format. This issue will be corrected during the data cleaning process.

#### Descriptive Statistics

In [69]:
df.describe().round(2)

       Transaction ID      Age  Quantity  Price per Unit  Total Amount
count         1000.00  1000.00   1000.00         1000.00        1000.0
mean           500.50    41.39      2.51          179.89         456.0
std            288.82    13.68      1.13          189.68         560.0
min              1.00    18.00      1.00           25.00          25.0
25%            250.75    29.00      1.00           30.00          60.0
50%            500.50    42.00      3.00           50.00         135.0
75%            750.25    53.00      4.00          300.00         900.0
max           1000.00    64.00      4.00          500.00        2000.0

This summary provides statistical information about the numerical columns, including:

- mean values,
- minimum and maximum values,
- quartiles,
- and standard deviation.

These statistics help identify the general distribution of the data and possible outliers.

#### Duplicate Rows Check

In [70]:
n_duplicated = df.duplicated().sum()
print(f"Duplicated rows: {n_duplicated}")

Duplicated rows: 0

No duplicated rows were found in the dataset, indicating that each transaction record is unique.

#### Missing Values Check

In [71]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

No missing values were detected in the dataset, which simplifies the data cleaning process and ensures that all records contain complete information.

#### Initial Data Inspection

In [72]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [73]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

The first and last rows of the dataset were reviewed to verify the consistency and structure of the data after loading.

#### Category Distribution

This analysis shows the number of transactions for each product category and helps identify the most common categories in the dataset.

**Observation**

The dataset appears to have a relatively balanced distribution across product categories, which is useful for comparative analysis.

In [74]:
print(df['Product Category'].value_counts())

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

#### Gender Distribution

This check was performed to understand the gender distribution of customers included in the dataset.

**Observation**

The gender distribution is relatively balanced, allowing comparisons between male and female purchasing behavior.

In [75]:
print(df['Gender'].value_counts())

Gender
Female    510
Male      490
Name: count, dtype: int64

#### Transaction Validation

This validation confirms that the Total Amount column was calculated correctly for all transactions.

$\text{Total Amount} = \text{Quantity} \times \text{Price per Unit}$

**Observation**

All transaction totals were consistent with the quantity purchased and the corresponding unit price, indicating good data integrity.

In [76]:
(df['Quantity'] * df['Price per Unit'] == df['Total Amount']).all()

np.True_

### Data Cleaning

During the initial assessment, it was identified that the `Date` column was stored as a string (`str`) instead of a datetime type.

To correct this issue, the column was converted to `datetime` format using `pd.to_datetime()`.

In [77]:
df_clean = df.copy()

In [78]:
df_clean["Date"] = pd.to_datetime(df_clean["Date"], errors="coerce")
df_clean["Date"].isna().sum()

np.int64(0)

The parameter `errors="coerce"` converts invalid date values into `NaT` (Not a Time), which makes problematic records easier to detect and handle during the cleaning process.

**Observation**

After the conversion, no invalid date values were detected, indicating that the Date column was successfully transformed into `datetime` format.

#### Invalid Datetime Check

In [79]:
df_clean[df_clean["Date"].isna()]

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

This check was performed to identify rows with invalid or missing datetime values after the conversion process.

Since no rows were returned, no invalid date values were found in the dataset.

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [81]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[us]
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[us](1), int64(5), str(3)
memory usage: 70.4 KB

The comparison between the original and cleaned DataFrames confirms that the Date column was successfully converted from `str` to `datetime64[ns]`.

**Observation**

The conversion improves the dataset structure and enables future time-based analysis such as monthly grouping, trend analysis, and date filtering.

#### Updated Descriptive Statistics

In [82]:
df_clean.describe()

,Transaction ID,Date,Age,Quantity,Price per Unit,Total Amount
count,1000.000000,1000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,2023-07-03 00:25:55.200000,41.39200,2.514000,179.890000,456.000000
min,1.000000,2023-01-01 00:00:00,18.00000,1.000000,25.000000,25.000000
25%,250.750000,2023-04-08 00:00:00,29.00000,1.000000,30.000000,60.000000
50%,500.500000,2023-06-29 12:00:00,42.00000,3.000000,50.000000,135.000000
75%,750.250000,2023-10-04 00:00:00,53.00000,4.000000,300.000000,900.000000
max,1000.000000,2024-01-01 00:00:00,64.00000,4.000000,500.000000,2000.000000
std,288.819436,NaN,13.68143,1.132734,189.681356,559.997632

After the data cleaning process, descriptive statistics were reviewed again to verify the consistency of the numerical columns and ensure that the dataset remained valid after the transformations.

#### Cleaned Dataset Preview

In [83]:
df_clean.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

The cleaned dataset was reviewed to verify that the transformations were applied correctly and that the overall structure remained consistent.

**Insight**

Converting columns to appropriate data types improves data consistency and enables more efficient filtering, grouping, and time-based analysis operations.

It also prepares the dataset for future stages such as visualization and predictive modeling.

## Data Transformation

### Create New Columns

New columns were created from existing variables in order to generate more useful metrics and improve the analytical capabilities of the dataset.

These transformations help simplify comparisons between customers, spending behavior, and product pricing levels.

---

#### Normalize Sales

The Total Amount column was normalized using Min-Max normalization to scale values between 0 and 1.

$x' = \frac{x − x_{min}}{x_{max} - x_{min}} $

In [84]:
df_clean['Total Amount Normalized'] = (
    (df_clean['Total Amount'] - df_clean['Total Amount'].min()) /
    (df_clean['Total Amount'].max() - df_clean['Total Amount'].min())
)

In [195]:
df_clean[[
    'Transaction ID',
    'Total Amount',
    'Total Amount Normalized'
]].head()

   Transaction ID  Total Amount  Total Amount Normalized
0               1           150                 0.063291
1               2          1000                 0.493671
2               3            30                 0.002532
3               4           500                 0.240506
4               5           100                 0.037975

**Insight**

Normalization makes values easier to compare by placing all transaction amounts within the same scale. This technique is especially useful for future machine learning and predictive modeling tasks.

#### Age Group

Customers were divided into age ranges to simplify demographic analysis.

In [175]:
df_clean['Age Group'] = pd.cut(
    df_clean['Age'],
    bins = [0, 25, 35, 50, 100],
    labels = ['Young adult', 'Adult', 'Middle age', 'Senior']
)

In [215]:
df_clean[[
    'Age',
    'Age Group',
    'Product Category',
    'Total Amount'
]].head()

   Age   Age Group Product Category  Total Amount
0   34       Adult           Beauty           150
1   26       Adult         Clothing          1000
2   50  Middle age      Electronics            30
3   37  Middle age         Clothing           500
4   30       Adult           Beauty           100

**Insight**

Grouping customers by age makes it easier to identify spending patterns and purchasing behavior across different demographic groups.

#### Spending Category

Transactions were classified into spending levels based on the `Total Amount` column.

In [197]:
df_clean['Spending Category'] = pd.cut(
    df_clean['Total Amount'],
    bins = [0, 100, 500, df_clean['Total Amount'].max()],
    labels = ['Low', 'Medium', 'High'],
    include_lowest = True
)

In [217]:
df_clean[[
    'Total Amount',
    'Spending Category'
]].head()

   Total Amount Spending Category
0           150            Medium
1          1000              High
2            30               Low
3           500            Medium
4           100               Low

**Insight**

This categorization helps distinguish low, medium, and high spending transactions, allowing easier comparison of customer purchasing behavior.

#### Price Tier

Products were grouped into pricing levels according to their unit price.

In [ ]:
df_clean['Price Tier'] = pd.cut(
    df_clean['Price per Unit'],
    bins = [0, 50, 200, df_clean['Price per Unit'].max()],
    labels = ['Budget', 'Standard', 'Premium'],
    include_lowest = True
)

In [218]:
df_clean[[
    'Price per Unit',
    'Price Tier'
]].head(10)

   Price per Unit Price Tier
0              50     Budget
1             500    Premium
2              30     Budget
3             500    Premium
4              50     Budget
5              30     Budget
6              25     Budget
7              25     Budget
8             300    Premium
9              50     Budget

**Insight**

Price segmentation helps identify the distribution of low-cost, mid-range, and premium products within the dataset.

It also supports future comparisons between pricing levels and customer spending behavior.

### Grouping and Aggregation

#### Sales By Month (`sum`)

Monthly sales totals were calculated to identify sales trends throughout the year.

In [201]:
df_clean['Month Number'] = df_clean['Date'].dt.month
df_clean['Month'] = df_clean['Date'].dt.month_name()

In [202]:
months_order = [
    'January', 'February', 'March', 'April',
    'May', 'June', 'July', 'August',
    'September', 'October', 'November', 'December'
]

df_clean['Month'] = pd.Categorical(
    df_clean['Month'],
    categories = months_order,
    ordered = True
)

In [203]:
df_clean[[
    'Transaction ID',
    'Product Category',
    'Total Amount',
    'Month',
    'Month Number'
]].head()

   Transaction ID Product Category  Total Amount     Month  Month Number
0               1           Beauty           150  November            11
1               2         Clothing          1000  February             2
2               3      Electronics            30   January             1
3               4         Clothing           500       May             5
4               5           Beauty           100       May             5

In [204]:
monthly_sales = df_clean.groupby('Month')['Total Amount'].sum()

In [205]:
monthly_sales

Month
January      36980
February     44060
March        28990
April        33870
May          53150
June         36715
July         35465
August       36960
September    23620
October      46580
November     34920
December     44690
Name: Total Amount, dtype: int64

**Observation**

May presented the highest total sales amount, while September recorded the lowest sales performance.

**Insight**

This analysis helps identify the months with the highest and lowest sales performance. Monthly aggregation is commonly used in retail analysis to detect seasonal trends and variations in customer purchasing behavior.

#### Average Spending By Age Group (`mean`)

The average transaction amount was calculated for each age group to compare customer spending behavior across different demographic segments.

In [206]:
df_clean.groupby('Age Group')['Total Amount'].mean().round(2)

Age Group
Young adult    500.30
Adult          480.39
Middle age     446.20
Senior         425.91
Name: Total Amount, dtype: float64

**Observation**

Young adults presented the highest average spending, while seniors showed the lowest average transaction values.

**Insight**

The results show how spending behavior changes across age groups. Some groups may present higher average purchases, indicating stronger purchasing power or different buying preferences.

#### Transactions By Month (`count`)

The total number of transactions per month was calculated to analyze transaction frequency over time.

In [207]:
df_clean.groupby('Month')['Transaction ID'].count()

Month
January       78
February      85
March         73
April         86
May          105
June          77
July          72
August        94
September     65
October       96
November      78
December      91
Name: Transaction ID, dtype: int64

**Observation**

May recorded the highest number of transactions, while September presented the lowest transaction activity.

**Insight**

This analysis helps identify periods with higher customer activity and allows comparison between transaction volume and total sales performance.

#### Spending Variability by Category (`std`)

The standard deviation of transaction amounts was calculated for each product category.

In [208]:
df_clean.groupby('Product Category')['Total Amount'].std().round(2)

Product Category
Beauty         563.61
Clothing       550.70
Electronics    567.54
Name: Total Amount, dtype: float64

**Observation**

All product categories presented similar levels of spending variability, indicating relatively consistent dispersion in transaction amounts across categories.

**Insight**

Standard deviation measures how dispersed transaction values are within each category.

$\sigma = \sqrt{ \frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2 }$


Higher values indicate greater variability in customer spending, while lower values suggest more consistent purchasing patterns.

#### Average Quantity by Product Category (`mean`)

The average quantity purchased was calculated for each product category.

In [209]:
df_clean.groupby('Product Category')['Quantity'].mean().round(2)

Product Category
Beauty         2.51
Clothing       2.55
Electronics    2.48
Name: Quantity, dtype: float64

**Observation**

The average quantity purchased was very similar across all product categories, with Clothing showing a slightly higher average quantity.

**Insight**

This analysis helps identify which categories are usually purchased in larger quantities and provides additional insight into customer buying behavior.

### Custom Analysis with `apply()`

#### Deviation from Group Mean

The deviation of each transaction from the average value of its product category was calculated.

In [210]:
df_clean['Deviation from Group Mean'] = (
    df_clean.groupby('Product Category')['Total Amount']
    .apply(lambda x: x - x.mean())
    .reset_index(level = 0, drop = True) # put the indices back in alignment with the dataframe
)

In [211]:
df_clean[[
    'Customer ID',
    'Product Category',
    'Total Amount',
    'Deviation from Group Mean'
]].head()

  Customer ID Product Category  Total Amount  Deviation from Group Mean
0     CUST001           Beauty           150                -317.475570
1     CUST002         Clothing          1000                 556.752137
2     CUST003      Electronics            30                -428.786550
3     CUST004         Clothing           500                  56.752137
4     CUST005           Beauty           100                -367.475570

**Observation**

Positive deviation values represent transactions above the category average, while negative values indicate transactions below the average.

The calculation follows the formula:

$x_i = \bar{x}_{group}$


**Insight**

Positive values indicate transactions above the category average, while negative values represent transactions below the average.

This type of analysis helps identify unusually high or low purchases within each product category.

#### Detect High-Value Transactions

Transactions were classified according to whether their value was above or below the overall average sales amount.

In [212]:
mean_sales = df_clean['Total Amount'].mean()

In [213]:
df_clean['High Value Transaction'] = df_clean['Total Amount'].apply(
    lambda x: 'Yes' if x > mean_sales else 'No'
)

In [214]:
df_clean[[
    'Customer ID',
    'Product Category',
    'Total Amount',
    'High Value Transaction'
]].head()

  Customer ID Product Category  Total Amount High Value Transaction
0     CUST001           Beauty           150                     No
1     CUST002         Clothing          1000                    Yes
2     CUST003      Electronics            30                     No
3     CUST004         Clothing           500                    Yes
4     CUST005           Beauty           100                     No

**Observation**

Transactions with amounts above the overall average sales value were classified as high-value transactions.

**Insight**

This classification introduces a simple benchmarking approach that helps distinguish higher-value purchases from regular transactions.

It can also support future analysis related to customer segmentation and spending behavior.

## Final Summary

In this project, the retail sales dataset was explored and analyzed using the Pandas library.

Several data preparation and transformation techniques were applied, including:

- data type conversion,
- creation of new analytical columns,
- normalization,
- grouping and aggregation,
- and custom analysis using the `apply()` method.

The analysis allowed the identification of sales patterns across months, age groups, and product categories. Statistical measures such as averages, standard deviation, and transaction counts were also used to better understand customer purchasing behavior and sales distribution.

Additionally, the dataset was prepared for future stages involving data visualization, exploratory analysis, and predictive modeling techniques.

## Acknowledgements

I would like to acknowledge the assistance provided by AI-based tools during the development of this project. These tools were helpful for understanding Pandas functions, improving data analysis techniques, and refining the structure and documentation of the notebook.

All code execution, analysis, interpretation, and final decisions were reviewed and adapted as part of the learning process.