# Retail Store Sales Analysis using Pandas (Core)

Author: Helene Schmelzer

Development Date: 05-05-2026

## Introduction to the Project

In this stage of the project, students will perform an initial analysis of a retail store sales dataset using the Pandas library. The focus is on applying fundamental concepts such as data inspection, data cleaning, and basic exploratory analysis.

Through this exercise, students will learn how to examine the structure and quality of a dataset, identify potential issues, and begin extracting simple insights from sales data.

This stage serves as a foundation for future work, where students will build on these skills to create visualizations, perform more advanced analysis, and develop predictive models.

## Dataset Description

In this project, we will use the Retail Sales Dataset (2023–2024) available on Kaggle. This dataset contains detailed records of daily sales transactions from a retail store, including information about products, quantities sold, pricing, and dates.

It provides a realistic scenario for practicing data analysis, allowing students to explore sales patterns, product performance, and basic business insights.

The dataset can be downloaded from Kaggle:
https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset

## Part 1: Basic Analysis with Pandas

## Previous analysis

### Dataset Availability and Path Setup

In [39]:
from pathlib import Path

In [40]:
data_dir = Path("../data")

# List available files (for verification)
available_files = list(data_dir.iterdir())
print("Available files:", available_files)

Available files: [WindowsPath('../data/retail_sales_dataset.csv')]

In [41]:
file_name = "retail_sales_dataset.csv"
dataset_path = data_dir / file_name

# Validate dataset existence
if not dataset_path.exists():
    raise FileNotFoundError(f"{file_name} not found in {data_dir}")

print("Dataset found at:", dataset_path)

Dataset found at: ..\data\retail_sales_dataset.csv

In this part, we start working with Pandas to explore the dataset.

Previous Setup

Before starting, we already:

- Installed Pandas
- Downloaded the dataset from Kaggle
- Placed the file in the working directory

Now we import Pandas:

In [42]:
import pandas as pd

### Data Loading

The dataset is loaded into a Pandas DataFrame from a CSV file:

In [43]:
df = pd.read_csv(dataset_path)

In [44]:
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

The first 10 rows are displayed to get a quick look at the data.

### Initial Data Assessment

We explored the dataset to understand its structure and check for possible issues.

In [45]:
print(f"{file_name}")
print(f"Shape: {df.shape}")
print(f"→ {df.shape[0]} rows, {df.shape[1]} columns\n")

retail_sales_dataset.csv
Shape: (1000, 9)
→ 1000 rows, 9 columns

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [47]:
df.describe().round(2)

       Transaction ID      Age  Quantity  Price per Unit  Total Amount
count         1000.00  1000.00   1000.00         1000.00        1000.0
mean           500.50    41.39      2.51          179.89         456.0
std            288.82    13.68      1.13          189.68         560.0
min              1.00    18.00      1.00           25.00          25.0
25%            250.75    29.00      1.00           30.00          60.0
50%            500.50    42.00      3.00           50.00         135.0
75%            750.25    53.00      4.00          300.00         900.0
max           1000.00    64.00      4.00          500.00        2000.0

In [48]:
n_duplicated = df.duplicated().sum()
print(f"Duplicated rows: {n_duplicated}")

Duplicated rows: 0

We did not find duplicated rows.

In [49]:
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [50]:
df.tail()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [51]:
print(df['Product Category'].value_counts())

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [52]:
print(df['Gender'].value_counts())

Gender
Female    510
Male      490
Name: count, dtype: int64

In [53]:
(df['Quantity'] * df['Price per Unit'] == df['Total Amount']).all()

np.True_

We found that the Date column was stored as a string, so we converted it to datetime format:

In [54]:
df_clean = df.copy()

In [55]:
df_clean["Date"] = pd.to_datetime(df_clean["Date"], errors="coerce")
df_clean["Date"].isna().sum()

np.int64(0)

In [56]:
df_clean[df_clean["Date"].isna()]

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [58]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[us]
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[us](1), int64(5), str(3)
memory usage: 70.4 KB

In [59]:
df_clean.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

We also checked if the word "Manzana" appears in any text column.

In [60]:
# Check if "Manzana" appears in any string column
str_cols = df.select_dtypes(include="str")

In [61]:
for col in str_cols.columns:
    if str_cols[col].str.contains("Manzana", case=False, na=False).any():
        print(f"'Manzana' found in column: {col}")

### Data Inspection

Some expected columns like `Producto` and `Tienda` were not found in the dataset.

Instead, we worked with the available `Product Category` column, assuming it represents different store sections or departments.

In [62]:
df_clean.dtypes

Transaction ID               int64
Date                datetime64[us]
Customer ID                    str
Gender                         str
Age                          int64
Product Category               str
Quantity                     int64
Price per Unit               int64
Total Amount                 int64
dtype: object

In [63]:
df_clean['Product Category'].value_counts()

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [64]:
df_clean['Product Category'].unique()

<StringArray>
['Beauty', 'Clothing', 'Electronics']
Length: 3, dtype: str

## Data Filtering

We applied different conditions to filter the dataset and explore specific cases.

Since `Ventas` and `Precio` were not available, `Total Amount` and `Price per Unit` were used as their equivalents for filtering.

The dataset does not contain a product named `Manzana`, so this condition could not be applied. Instead, a similar filter was tested using an available category (`Electronics`) with a higher sales condition.

In [65]:
condition = df_clean['Total Amount'] > 50

df_clean[condition]

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
...,...,...,...,...,...,...,...,...,...
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [66]:
condition = df_clean['Price per Unit'] < 0.5

df_clean[condition]

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

In [67]:
condition = "(`Product Category` == 'Electronics') and (`Total Amount` > 100)"

df_clean.query(condition)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
25,26,2023-10-07,CUST026,Female,28,Electronics,2,500,1000
30,31,2023-05-23,CUST031,Male,44,Electronics,4,300,1200
...,...,...,...,...,...,...,...,...,...
969,970,2023-05-16,CUST970,Male,59,Electronics,4,500,2000
970,971,2023-12-05,CUST971,Female,27,Electronics,4,50,200
992,993,2023-02-06,CUST993,Female,48,Electronics,3,50,150
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

## Data Slicing

Different slicing techniques were used to select specific rows and columns from the dataset.

Since `Producto` and `Tienda` were not available, `Product Category` was used as a reference. This column was treated as a general representation of product-related information for the slicing examples.

In [68]:
df_clean[['Price per Unit', 'Total Amount']]

     Price per Unit  Total Amount
0                50           150
1               500          1000
2                30            30
3               500           500
4                50           100
..              ...           ...
995              50            50
996              30            90
997              25           100
998              50           150
999              30           120

[1000 rows x 2 columns]

In [69]:
df_clean[['Product Category']].loc[5:10]

   Product Category
5            Beauty
6          Clothing
7       Electronics
8       Electronics
9          Clothing
10         Clothing

In [70]:
df_clean.iloc[0:5, 0:3]

   Transaction ID       Date Customer ID
0               1 2023-11-24     CUST001
1               2 2023-02-27     CUST002
2               3 2023-01-13     CUST003
3               4 2023-05-21     CUST004
4               5 2023-05-06     CUST005

## Acknowledgements

I would like to thank ChatGPT for the support during this assignment. It helped me improve the clarity of my explanations, correct my English, and keep my original ideas while suggesting how to handle missing columns or values like "Manzana".